forever(() => {
    // Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
    modules.yahboomBackLeds.setBrightness(100)
    modules.yahboomBackLeds.setAll(0x0000ff)
    console.log(modules.yahboomBackLeds.brightness())
//    modules.yahboomFrontLeds.setBrightness(100)
 //   modules.yahboomFrontLeds.setAll(0xff0000)
    pause(500)
    // Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
    modules.yahboomBackLeds.setAll(0xff0000)
//    modules.yahboomFrontLeds.setAll(0x0000ff)
  //  basic.clearScreen()
  //  if (modules.yahboomLineLeft.brightness() > 0)
   //     led.plot(0, 1)
   // if (modules.yahboomLineRight.brightness() > 0)
    //    led.plot(4, 1)
 //   music.playTone(440, 100)
    pause(500)
})

control.runInBackground(() => {
    modules.yahboomBackLeds.onConnected(() => {
        console.log("back light connected")
    })
})