forever(() => {
    led.toggle(0, 0)
    modules.yahboomBackLeds.setBrightness(99)
    modules.yahboomFrontLeds.setBrightness(99)
    modules.yahboomBackLeds.setAll(0x0000ff)
    modules.yahboomFrontLeds.setAll(0xff0000)
    pause(500)
    modules.yahboomBackLeds.setAll(0xff0000)
    modules.yahboomFrontLeds.setAll(0x0000ff)
    //  basic.clearScreen()
    if (modules.yahboomLineLeft.brightness() > 0)
        led.plot(0, 1)
    if (modules.yahboomLineRight.brightness() > 0)
        led.plot(4, 1)
    //   music.playTone(440, 100)
    console.logValue(`distance`, modules.yahboomSonar.distance())
    console.logValue('sound', modules.yahboomMicrophone.soundLevel())
    led.plotBarGraph(modules.yahboomMicrophone.soundLevel(), 100)
    pause(500)
})

control.runInBackground(() => {
    modules.yahboomBackLeds.onConnected(() => {
        console.log("back light connected")
    })
})